mirleft/ocaml-x509

lib/certificate.ml
lib/certificate.mli

make errors more precise by passing relevant certificate(s)

remove Printf.printf

---

lib/certificate.ml
lib/certificate.mli

- don't check extensions in self-signed certificates when TOFU
- extract verify_chain function to deduplicate code

Fingerprint verification fixes

---

lib/x509.ml
lib/x509.mli

As of right now, there is no need to have the `Authenticator.t` abstract. It just prevents people from writing their own.
If and when we come up with a neat algebra for authenticators, they can get abstract again.

Make the authenticator type manifest

---

lib/certificate.ml
lib/certificate.mli

for marshalling a certificate (namely its SHA256 fingerprint)

provide sexp conversions of certificate_failure, also sth useful

---

lib/x509.ml
lib/x509.mli

`Authenticator.t` should do its own sexp conversions even if it's stubs.

Authenticator sexp

---

lib/asn_grammars.ml
lib/x509_pem.ml

are neither encrypted nor contain attributes

support PKCS8 privateKeyInfo, for now only RSA private keys which

---

lib/x509.mli

This expands the documentation of X509.CS.sign following the discussion
in #63.

documentation: X509.CA.sign and CSR extensions

---

lib/x509.mli
lib/x509_certificate.ml

This patch exposes the fingerprint of the hash of the X509.t certificate.
The user must specify the desired hashing algorithm.
```ocaml
(** [fingerprint cert hash] is [Cstruct.t],
a hash digest of [cert] produced by the [hash] algorithm *)
val fingerprint : t -> Nocrypto.Hash.hash -> Cstruct.t
```
Example usage:
```ocaml
X509.fingerprint cert `SHA256
```

expose certificate hash fingerprint in X509.fingerprint

---

lib/x509.mli
lib/x509_authenticator.ml
lib/x509_certificate.ml

instead of pinning certificates, allow pinning of public keys of leaf certificates (leaving certificate pinning around, but marked as deprecated, to be removed in next major release). addresses #68.  Also introduces `key_fingerprint : ?hash -> public_key -> Cstruct.t`, which produces the digest of the DER encoded public key (including algorithmIdentifier etc, thus unfortunately different from `key_id`, what a mess)

public key fingerprint

---

lib/x509.mli
lib/x509_certificate.ml
tests/regression.ml
tests/x509tests.ml

in congruence to the real world, this PR accepts arbitrarily ordered certificate chains, instead of requiring `server :: issuer_of_server :: issuer_of_issuer_of_server :: ... :: []`, where the last certificate is signed by some trust anchor.  In reality these aren't strict chains anymore (there are practical reasons, such as phasing out SHA1 and MD5 signatures, while preserving compatibility with deployed trust anchors; thus `S -> A -> B -> C -> D` might be transmitted, where `S` is the leaf certificate, signed by `A`, which is signed both by `B -> C` rooted in some arcane trust anchor, and also by `D`, rooted in some modern trust anchor).
This also implements the informational RFC 4158, how to build paths.  A potential user can build paths manually, and verify each in order to receive …

Certificate ordering

---

lib/asn_grammars.ml
lib/x509.mli
lib/x509_encoding.ml

This adds `X509.Encoding.cs_of_cert_subject` which is required for https://github.com/mirleft/ocaml-tls/pull/332

Add css_of_distinguished_name

---

.ocamlinit
.travis.yml
_tags
lib/asn_grammars.ml
lib/x509.mli
lib/x509_certificate.ml
lib/x509_extension.ml
opam
pkg/META

this PR
a) provides a function to extract the unsupported extension (for unknown/unhandled OIDs)
b) fixes the raw_signature_hack to work with large certificates (where 4 bytes is not a good estimate for the length of the certificate) by peeking into the actual number.  of course this is still a hack, but a good improvement over the existing one

support `unsupported` extensions

---

lib/x509.mli

`X509_types` is not exposed, so without this change users can't create `distribution_point_name`s or `distribution_point`s.

use distinguished_name, not X509_types.distinguished_name, in x509.mli

---

myocamlbuild.ml
opam
pkg/META.in

this uses the same myocamlbuild as nocrypto + tls to support ppx_sexp_conv > v0.11.0 which inserted runtime dependencies.  this makes x509 fit for 4.07.0

compatibility with ppx_sexp_conv > v0.11.0

---

CHANGES.md
lib/distinguished_name.ml
lib/x509.mli
tests/regression.ml

This is my suggestion for an improved DN pretty-printing, with some reservations:
1. I still cannot find any specifications for the OSF DN format, so that was designed in analogy with the RFC format and what I know from working with such DNs.  The uncertain part is escaping rules.  I consequently switched the default `pp` to the RFC format.
2. It should be noted that openssl uses something which looks like RFC 4514 but prints the RDNs in opposite order, e.g. `openssl -issuer` of by own cert is `C = NL, ST = Noord-Holland, L = Amsterdam, O = TERENA, CN = TERENA eScience Personal CA 3`.  I think this is a source of ambiguity, since its hard for a parser to determine which order is used, apart from heuristics on certain attribute-types. The OpenSSL order would have been better, but section …

Improve pretty-printer for DNs (RFC 4514 and OSF).

---

CHANGES.md
lib/certificate.ml
lib/distinguished_name.ml
lib/extension.ml
lib/x509.mli

also expose `Distinguished_name.common_name : t -> string option` (I have some revdeps which use exactly this) //cc @paurkedal

Pretty printers for extensions

---

CHANGES.md
lib/distinguished_name.ml
lib/registry.ml
lib/x509.mli
tests/regression.ml

- STREET was missing
- stateorprovince is usually ST, not SP
- UID was missing
//cc @paurkedal

conform to RFC 4514 by supporting all required distinguished name attribute types

---

lib/authenticator.ml
lib/certificate.ml
lib/crl.ml
lib/signing_request.ml
lib/validation.ml
lib/x509.mli
tests/crltests.ml
tests/regression.ml
tests/revoke.ml
tests/x509tests.ml

fixes #123
for @psafont I added ``val signature_algorithm : t -> ([ `RSA | `ECDSA ] * Nocrypto.Hash.hash) option`` to the Certificate, Signing_request, and CRL modules. Does this suite you well?
The (chain) validation functions now receive an optional `hash_whitelist` argument, which the signature algorithm must match. The default is any SHA-2 algorithm (SHA256/SHA384/SHA512, _not_ SHA224 - seems to be rarely used, I could not see a reason to include it). The default for `valid_ca{,s}` is any hash algorithm (following what others are doing).
/cc @emillon @paurkedal for a quick round of review -- this certainly changes the behaviour of x509 & tls -- in a good way forward (rejecting weak algorithms by default).

hash algorithms used for signatures

---

lib/certificate.ml
lib/crl.ml
lib/dune
lib/public_key.ml
lib/signing_request.ml
lib/validation.ml
lib/x509.mli
tests/crltests.ml
tests/regression.ml
tests/revoke.ml
x509.opam

also, even if hash_whitelist contains a weak algorithm, print a log message
(warning level) about the usage of the weak algorithm
//cc @cfcs -- we discussed this

expose more detailed signature errors

---

lib/x509.mli

Open polymorphic variants to be able to compose `('a, [> Validation.signature_error ]) result` with `('a, [> R.msg ]) result`. I got a compilation error with `albatross` - where it wants to compose with `R.msg`.

Be able to compose errors

---

lib/signing_request.ml
lib/x509.mli

Adds an optional argument `subject` to `X509.Signing_request.sign`. The argument `subject` will override the subject field of the CSR for the resulting certificate.
I have tested with a patched version of ocaml-certify adding a test case and manually verifying the subject in the resulting certificate.
I am not happy with the documentation. I added `Public key and subject are taken from the [signing_request] ***unless [subject] is passed***, the [extensions] are added to the X.509 certificate`. I'll reword and update the PR.

Allow change of subject when signing CSR

---

lib/crl.ml
lib/x509.mli

This is to avoid warning 16 (defaults to be enabled with 4.12).

CRL: move [crls] argument in CRL.is_revoked to the last position

---

lib/authenticator.ml
lib/validation.ml
lib/x509.mli

Previously a list of name and fingerprint was passed, which was not used at all.
In practice, a single fingerprint is sufficient. With this change, providing the
fingerprint of a certificate that is valid for certain IP addresses will work
nicely (similar to what #152 does for chain of trust).
//cc @reynir

simplify fingerprint validation and authentication: pass a single fingerprint

---

lib/private_key.ml
lib/x509.mli
tests/priv.ml
tests/tests.ml

This decodes a string to a private key - depending on the key type using
either of_cstruct or generate (by default), allowing ~seed_or_data being
passed explicitly.
https://github.com/mirage/awa-ssh/pull/39
https://github.com/mirage/ocaml-dns/commit/06d878037176b24ef55264fbae2b3bceeefa9033

Add X509.Private_key.of_string function, as used in awa-ssh and dns-certify

---

lib/authenticator.ml
lib/x509.mli

Related to [mirage/ocaml-dns](https://github.com/mirage/ocaml-dns/pull/297#discussion_r805649032). A simple function which tries to deserialize a string to an `Authenticator.t`.

Add Authenticator.of_string

---

lib/validation.ml

`hash algorithm /CN=snakeoil is not allowed, but SHA224 is signed using it` is a funny but confusing error message :D

Fix mixup of subject and hash in error message

---

lib/certificate.ml
lib/pem.ml
lib/x509.mli

Following https://github.com/mirage/ca-certs/pull/30, @hannesm suggested that the handling of certificate parse errors from `pem` would be better handled in X509 than in `ca-certs`, as the parsing logic there is less complete than in X509, with no support for `\r\n` for example, but there's a need to ignore parse errors which wasn't possible before with x509 api alone.

Add Certificate.fold_decode_pem_multiple

---

lib/signing_request.ml

/cc @dinosaure -- I prefer this over #178, the reason being that I'm scared of introducing recursive functions.
would be great if you could have a look at this!?

fix the serial rng
